Commented out the rest of data persistence, to get rid of this:
04/04/03 13:28:48 ERROR Exception Checkpointing!
Traceback (most recent call last):
  File "/usr/lib/python2.2/site-packages/AccessGrid/VenueServer.py", line 691, in Checkp
oint
    store.write(self.venues[venuePath].AsINIBlock())
  File "/usr/lib/python2.2/site-packages/AccessGrid/Venue.py", line 150, in AsINIBlock
    string += "data : %s\n" % dlist
NameError: global name 'dlist' is not defined
cvs: ----------------------------------------------------------------------
cvs: enter log.  lines beginning with `cvs:' are removed automatically