Changes to properly categorize bugs (into node setup, venue mgmt, and a heuristic to attempt to catch GSI bugs and file as certificate mgmt).
Needs a fix in UIUtilities to the SubmitBug calls:



  File "C:\home\olson\ag\dev\March10\AccessGrid\AccessGrid\UIUtilities.py", line
 59, in __init__
    SubmitBug(comment,  email, logFile)
TypeError: SubmitBug() takes at least 4 arguments (3 given)